### ISSUE TITLE
Operating the selector automatically moves the selected track to the target track

### ISSUE THREAD

**Issue by IceflameCat** [zsteinkamp/m4l-ChiasticSolo#1] opened 2024-11-21 16:47 UTC
As the title described, when I move the selector knob, the selected track jumps to the one that the knob indicates, which makes it difficult to use. Also moving the cursor onto this device causes it to jump around.

The video of this behaviour is attached as a file.

Otherwise a really cool idea! Love your work ;D

https://github.com/user-attachments/assets/0a771e2a-a2e5-449a-ad41-512bb7b5b22c

**Comment by zsteinkamp** [comment] 2024-11-21 20:21
Thank you @IceflameCat ! That is very weird! I appreciate the video and will look into this right now. What OS and version of Live are you on?

**Comment by zsteinkamp** [comment] 2024-11-21 20:22
I am able to reproduce it here. Guessing it's a Live 12 thing, since I haven't used it since I upgraded and it was behaving correctly in 11. Will let you know what I find. Hopefully a fix is possible. 🤞

**Comment by zsteinkamp** [comment] 2024-11-21 21:32
Yeah if I comment out the lines that trigger the `solo`, then the problem disappears, but then the device is useless. 

```diff
diff --git a/chiasticSolo.js b/chiasticSolo.js
index 2447cc7..d0e649d 100644
--- a/chiasticSolo.js
+++ b/chiasticSolo.js
@@ -58,10 +58,10 @@ function updateSolos() {
       continue
     }
     if (state.enabled && i === state.val) {
-      state.chains[i].set('solo', 1)
+      //state.chains[i].set('solo', 1)
       outlet(OUTLET_VAL, [i + 1, 1])
     } else {
-      state.chains[i].set('solo', 0)
+      //state.chains[i].set('solo', 0)
       outlet(OUTLET_VAL, [i + 1, 0])
     }
   }
```
I will look through the Live 12 docs to see if there is a different property or method to call, and if there is nothing there then I will file a bug with Ableton. Will update here with progress.

**Comment by zsteinkamp** [comment] 2024-11-21 22:08
Here is a minimal device example showing how the `solo` property steals and messes with focus.

https://steinkamp.us/dropbox/soloDemo.amxd

First click a track, then click the solo buttons. I'll file a bug report with this and put a BIG NOTE in the readme of the repo that this only works with 11 at the moment. Thanks!

**Comment by IceflameCat** [comment] 2024-11-22 04:45
> Thank you @IceflameCat ! That is very weird! I appreciate the video and will look into this right now. What OS and version of Live are you on?

I'm currently on Windows 11 and Live 12.1.1
I've been browsing everywhere and looking for similar issues, and it seems like Live 12 might have a fundamentally different way of handling focus while soloing tracks...? Because even when hitting solo for a differernt track on my controller also triggers this weird thing...

**Comment by zsteinkamp** [comment] 2024-11-22 05:00
Same with soloing via the Push2 here, so I think you're right. I'll share what Ableton says in response to my bug report.

**Comment by zsteinkamp** [comment] 2024-11-22 15:49
Got this response from Ableton support:

Hello there,
 
Thanks for your patience while we investigated the issue you reported:
 
Regression: In Live 12, soloing a Track also selects the track.
 
We have determined that the issue at hand is not a bug and is actually expected behavior. Therefore, it currently requires no further attention and this ticket will be closed.
 
With this in mind, there is an option available to use the previous Solo functionality:
`-NoHighlightOnSolo`
 
To use this option, please review the following knowledge base article:
[Options.txt file](https://help.ableton.com/hc/en-us/articles/6003224107292-Options-txt-file?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5MDM1NDcsInVzZXJfaWQiOjM3ODUxOTkyMjY5OSwidGlja2V0X2lkIjoyOTIzODgxLCJjaGFubmVsX2lkIjo2MywidHlwZSI6IlNFQVJDSCIsImV4cCI6MTcyMzI4NTI5Mn0.WxwezPitXs_GcXq9qs9Di47DDZ8Ek7ivgw6itTpBTKw)
 
We hope that this is acceptable to you, but if you have any questions, feel free to write back to us!

**Comment by zsteinkamp** [comment] 2024-11-22 15:57
I can confirm that the issue is fixed by adding this line:
```
-NoHighlightOnSolo
```
to an `options.txt` file located in `~/Preferences/Ableton/Live\ 12.1.1` (adjust the path to the exact version of Live you are using).

I'll update the README.md file with this instruction for Live 12 users. Thanks for opening the issue!

**Closed as completed by zsteinkamp** 2024-11-22 15:57 UTC

**Comment by IceflameCat** [comment] 2024-11-22 16:11
Oh my... That fixed it!

This behaviour change easily went under the radar though, options.txt seems to be more of a debug tool and this is really easy to miss among all the changelog text (and honestly it's slightly annoying \*shrugs\*).

Still, thanks for updating with this info! Definnitely gonnna use this device extensively now :)

**Comment by zsteinkamp** [comment] 2024-11-22 16:14
Glad it worked for you :) 

Curious what your use case is for it? 

I made it to easily flip between tracks in an album while mixing/mastering (hah if you can call it that!) to quickly check they are similar in loudness and tone.

**Comment by IceflameCat** [comment] 2024-11-22 16:31
I actually wanted to use it while producing and sound designing. I mainly produce Trance which is a genre that does a lot of layered sounds, and I would use this to switch swiftly between different layers and determine what should be cut or adjusted, and also just great for when I'm arranging drums so I can just solo loops one by one in order. Now I can use it more (and it feels quite satisfying! ;D)

**Comment by zsteinkamp** [comment] 2024-11-22 16:36
Sweet! Do you have a physical knob assigned to the selector dial?
Have you seen [Knobbler4](https://github.com/zsteinkamp/m4l-Knobbler4)?

**Comment by IceflameCat** [comment] 2024-11-22 16:45
Ah yes I've seen that! Looks really interesting but I currently have I small macro keyboard with a knob to do it, so I didn't think of usinng my iPad for that.
Could be really cool while traveling, though! Will definitely try it out some time!
